### ISSUE TITLE
Performance Misaligned with your paper.

### ISSUE THREAD

**Issue by guyuchao** [LeyRio/MIG_Bench#3]
Using the provided example, I can align the performance with your readme. However, the performance in the readme is different with your paper. What causes this difference?

<img width="1209" alt="Screenshot 2024-09-14 at 10 19 39 AM" src="https://github.com/user-attachments/assets/3d383e2b-107b-4594-97a9-6c46f6098672">

**Comment by LeyRio** [comment]
Thank you for your interest in our work. There are two reasons why the metrics in the README differ from those in the paper. First, when releasing the open-source version, we removed the "people" category from the benchmark because expressions like 'a red/green/yellow... people' seemed a bit odd. Second, the weights in the open-source version have stronger control capabilities compared to those in the paper, resulting in higher metrics.

**Comment by guyuchao** [comment]
thanks for reply
